Update to .NET 6 GA

diff --git a/build-dotnet-tarball b/build-dotnet-tarball
--- a/build-dotnet-tarball
+++ b/build-dotnet-tarball
@@ -1,11 +1,11 @@
 #!/bin/bash
 
 # Usage:
-#   build-dotnet-tarball [--bootstrap] <tag-from-source-build>
+#   build-dotnet-tarball [--bootstrap] <tag-from-installer>
 #
-# Creates a source archive from a tag (or commit) at github.com/dotnet/source-build
+# Creates a source archive from a tag (or commit) at github.com/dotnet/installer
 
-# Source-build is a little strange, we need to clone it, check out the
+# installer is a little strange, we need to clone it, check out the
 # tag, build it and then create a tarball from the archive directory
 # it creates. Also, it is likely that the source archive is only
 # buildable on the OS it was initially created in.
@@ -15,9 +15,9 @@ IFS=$'\n\t'
 
 function print_usage {
     echo "Usage:"
-    echo "$0 [--bootstrap] <tag-from-source-build>"
+    echo "$0 [--bootstrap] <tag-from-installer>"
     echo
-    echo "Creates a source archive from a tag at https://github.com/dotnet/source-build"
+    echo "Creates a source archive from a tag at https://github.com/dotnet/installer"
     echo ""
     echo "  --bootstrap     build a source tarball usable for bootstrapping .NET"
 }
@@ -102,14 +102,16 @@ set -x
 dir_name="dotnet-${tag}"
 unmodified_tarball_name="${dir_name}-original"
 tarball_name="${dir_name}"
+tarball_suffix=.tar.gz
 
 if [[ ${build_bootstrap} == true ]]; then
     unmodified_tarball_name="${unmodified_tarball_name}-${arch}-bootstrap"
     tarball_name="${tarball_name}-${arch}-bootstrap"
+    tarball_suffix=.tar.xz
 fi
 
-if [ -f "${tarball_name}.tar.gz" ]; then
-    echo "error: ${tarball_name}.tar.gz already exists"
+if [ -f "${tarball_name}${tarball_suffix}" ]; then
+    echo "error: ${tarball_name}${tarball_suffix} already exists"
     exit 1
 fi
 
@@ -125,15 +127,9 @@ if [ ! -f "${unmodified_tarball_name}.tar.gz" ]; then
     ./build.sh /p:ArcadeBuildTarball=true /p:TarballDir="$(readlink -f ../"${unmodified_tarball_name}")"
     popd
 
-    if [[ ${build_bootstrap} == true ]]; then
-        pushd "${unmodified_tarball_name}"
-        ./prep.sh
-        popd
-    fi
-
     popd
 
-    tar czf "${unmodified_tarball_name}.tar.gz" -C "${temp_dir}" "${unmodified_tarball_name}"
+    tar cf "${unmodified_tarball_name}.tar.gz" -C "${temp_dir}" "${unmodified_tarball_name}"
 
     rm -rf "${temp_dir}"
 fi
@@ -145,15 +141,36 @@ mv "${unmodified_tarball_name}" "${tarball_name}"
 pushd "${tarball_name}"
 
 if [[ ${build_bootstrap} == true ]]; then
+    if [[ "$(wc -l < packages/archive/archiveArtifacts.txt)" != 1 ]]; then
+        echo "error: this is not going to work! update $0 to fix this issue."
+        exit 1
+    fi
+
+    pushd packages/archive/
+    curl -O $(cat archiveArtifacts.txt)
+    popd
+
+    mkdir foo
+    pushd foo
+
+    tar xf ../packages/archive/Private.SourceBuilt.Artifacts.*.tar.gz
+    sed -i -E 's|<MicrosoftNETHostModelPackageVersion>6.0.0-rtm.21521.1</|<MicrosoftNETHostModelPackageVersion>6.0.0-rtm.21521.4</|' PackageVersions.props
+    sed -i -E 's|<MicrosoftNETHostModelVersion>6.0.0-rtm.21521.1</|<MicrosoftNETHostModelVersion>6.0.0-rtm.21521.4</|' PackageVersions.props
+    cat PackageVersions.props
+
+    tar czf ../packages/archive/Private.SourceBuilt.Artifacts.*.tar.gz *
+
+    popd
+    rm -rf foo
+
+    ./prep.sh --bootstrap
+
     mkdir -p fixup-previously-source-built-artifacts
     pushd fixup-previously-source-built-artifacts
     tar xf ../packages/archive/Private.SourceBuilt.Artifacts.*.tar.gz
     find . -iname '*fedora*nupkg' -delete
-    rm runtime.linux-x64.Microsoft.NETCore.IL*sm.*.nupkg
-    wget https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/flat2//runtime.linux-x64.Microsoft.NETCore.ILAsm/6.0.0-rc.2.21459.6/runtime.linux-x64.microsoft.netcore.ilasm.6.0.0-rc.2.21459.6.nupkg
-    wget https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/flat2//runtime.linux-x64.Microsoft.NETCore.ILDAsm/6.0.0-rc.2.21459.6/runtime.linux-x64.microsoft.netcore.ildasm.6.0.0-rc.2.21459.6.nupkg
     # We must keep the original file names in the archive, even prepending a ./ leads to issues
-    tar -I 'gzip -9' -cf ../packages/archive/Private.SourceBuilt.Artifacts.*.tar.gz *
+    tar -I 'gzip -1' -cf ../packages/archive/Private.SourceBuilt.Artifacts.*.tar.gz *
     popd
     rm -rf fixup-previously-source-built-artifacts
 
@@ -164,12 +181,26 @@ fi
 
 # Remove files with funny licenses, crypto implementations and other
 # not-very-useful artifacts to reduce tarball size
-# FIXME
-#rm -r src/aspnetcore.*/src/SignalR/clients/java/signalr/gradle*
-#find src/aspnetcore.*/src -type d -name samples -print0 | xargs -0 rm -r
-#rm -r src/nuget-client.*/test/EndToEnd
-#rm -r src/source-build.*/src/humanizer/samples/
+
+# Binaries for gradle
+rm -r src/aspnetcore.*/src/SignalR/clients/java/signalr/gradle*
+
+# Unnecessary crypto implementation: IDEA
+rm -r src/runtime.*/src/tests/JIT/Performance/CodeQuality/Bytemark/
+
+# https://github.com/dotnet/aspnetcore/issues/34785
+find src/aspnetcore.*/src -type d -name samples -print0 | xargs -0 rm -r
+
+# https://github.com/NuGet/Home/issues/11094
+rm -r src/nuget-client.*/test/EndToEnd
+
+# https://github.com/Humanizr/sample-aspnetmvc/issues/1
+rm -r src/source-build.*/src/humanizer/samples/
 
 popd
 
-tar -I 'gzip -9' -cf "${tarball_name}.tar.gz" "${tarball_name}"
+if [[ ${build_bootstrap} == true ]]; then
+    tar -I 'xz -T 0' -cf "${tarball_name}${tarball_suffix}" "${tarball_name}"
+else
+    tar -czf "${tarball_name}${tarball_suffix}" "${tarball_name}"
+fi
